### ISSUE TITLE
aborting a file in progress should not crash the server Mocha error

### ISSUE THREAD

**Issue by theo4u** [balderdashy/skipper-adapter-tests#3]
Having error with that part, as mocha don't allow error passed to done as done below in `abort.test.js:51`

Error returned in console:   ` Error: done() invoked with non-Error: The request should have returned an error! `

from this code below
 ```
function (res) {
        return done("The request should have returned an error!");
}
```

if changed to 
```
 function (res) {
        return done(); // it works , as mocha don't allow param in done callback which it would take as error
}
```

**Comment by sgress454** [comment]
Hi @theo4u -- I can see how this is confusing.  If you are seeing this message, the problem is with your adapter, not the test.  It means that the test is failing because the _request_ should have returned an error, and so line 51 should _never even run_ (see the comments on lines 48-49).  

Mocha is fine with calling `done` without an `Error` object; it just lets you know that you did.  What we should probably do is replace the line with:

```
return done(new Error('The request should have returned an error!'));
```

in which case if the test fails, you'll see:

```
Error: The request should have returned an error!
```

**Comment by theo4u** [comment]
Thanks

**Comment by mikermcneil** [comment]
This issue was moved to balderdashy/sails#4211
